### ISSUE TITLE
Error al enviar pago con Nequi

### ISSUE THREAD

**Issue by rchleonardo16** [reyesmfabian/wompi_payment#2]
![Captura de pantalla 2023-12-06 124656](https://github.com/reyesmfabian/wompi_payment/assets/64086560/5d65c2f2-4e5c-471f-bf6b-22ffc66ddde3)

Ojala me puedan ayudar

**Comment by reyesmfabian** [comment]
Este error fue solventado en la version 2.0.0.

**Comment by rchleonardo16** [comment]
![Captura de pantalla 2023-12-07 142610](https://github.com/reyesmfabian/wompi_payment/assets/64086560/19640b6a-f081-427f-a082-5f865d235f72)

Hola gracias por responder, pero se vuelve a presentar al enviar el pago con Nequi

**Comment by reyesmfabian** [comment]
De que forma estás haciendo la prueba contra Sandbox o Producción? Puedes subir el snippet de código en un nuevo Issue para revisarlo? Ayer hice varias pruebas y todo funcionó de manera correcta

**Comment by rchleonardo16** [comment]
Hola, hecho
