### ISSUE TITLE
Error al enviar pago con Nequi - wompi_payment 2.0.1

### ISSUE THREAD

**Issue by rchleonardo16** [reyesmfabian/wompi_payment#3]
Hola, comparto el código que estoy utilizando para probar los pagos pero este me muestra un error al momento de traer la respuesta del mismo.

--------------

import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:wompi_payment_colombia/wompi_payment_colombia.dart';

class WompiPage extends StatefulWidget {
  const WompiPage({super.key});

  @override
  State<WompiPage> createState() => _WompiPageState();
}

class _WompiPageState extends State<WompiPage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: ElevatedButton(
          style: ElevatedButton.styleFrom(
            padding: EdgeInsets.symmetric(horizontal: 50, vertical: 25),
          ),
          onPressed: () => _realizarPagoNequi(),
          child: const Text("Ejecutar pago", style: TextStyle(color: Colors.white)),
        ),
      ),
    );
  }

  _realizarPagoNequi() async{
      WompiClient wompiClient = WompiClient(
        publicKey: 'pub_test_XXXXXXX', // Business Public Key
        environment:
            Environment.TEST, // or Environment.TEST for testing purposes,
        businessPrefix: 'FR-', // Business Prefix
        currency: 'COP', // Currency for the payments
      );

      final acceptance = await WompiService.getAcceptance(wompiClient: wompiClient);

      final pdfTermsLink = acceptance.data.presignedAcceptance.permalink;

      final acceptanceToken = acceptance.data.presignedAcceptance.acceptanceToken;

      PaymentRequestData paymentRequestData = PaymentRequestData(
        email: "pruebas@mail.com", // The email of the user who will make the payment.
        phone: "3991111111", // The phone of the user who will make the payment.
        name: "Pruebas", // The name of the user who will make the payment.
        acceptanceToken:acceptanceToken, // The token that will be used to make the payment.
        reference: "TEST323456", // The reference of the payment.
        document:"1040000031" // The document of the user who will make the payment.
      );

      NequiPay nequiPay = NequiPay(
        paymentRequest: paymentRequestData, // Payment request data
        wompiClient: wompiClient, // Wompi client
        amount: 5000, // Amount to pay as integer
        phoneNumberToPay: "3991111111" // Phone number to pay
      );

 
      final NequiPaymentResponse nequiPayment = await WompiService.pay(paymentProcessor: nequiPay);

      final NequiCheckModel nequiCheck = await WompiService.checkPayment(
        paymentChecker: NequiCheck(
          transactionId: nequiPayment.data.id,
          wompiClient: wompiClient,
        ),
      );

  if (kDebugMode) {
    print(nequiCheck.data.status);
  }
  
  }
}

![Captura de pantalla 2023-12-07 142610](https://github.com/reyesmfabian/wompi_payment/assets/64086560/fe293df2-5fa0-49cd-a3ca-9baf7ec4b203)

**Comment by reyesmfabian** [comment]
Hola, los pagos se estaba reportando correctamente, parece que se habian cambiado algunos tiempos por parte de Wompi al momento de las respuestas.

Esto se ha corregido en la versión v2.1.0 disponible en breves.

**Comment by rchleonardo16** [comment]
Muchas gracias
